### ISSUE TITLE
Gitlab CI

### ISSUE THREAD

**Issue by itsecforu** [kramse/nmap-ci#1]
hey!

I've been trying to run nmap in docker on runner for a long time.

my job:

```
image: foo/bar:v1
script:
  - nmap --top-ports 20 -iL ./ip-list
```

Tryed with theese images:

- docker.io/cyberwatch/nmap                                                     
- docker.io/uzyexe/nmap                                                         
- docker.io/bytesizedalex/nmap 

every command like ``nmap -v``, `` nmap --top-port`` etc i get error:

``nmap: unrecognized option: c``

can you have experience of launching in Docker and can you help me with this?

**Comment by kramse** [comment]
Those are not my images, perhaps try
https://github.com/kramse/nmap-ci/blob/master/docker-images/nmap-ci/Dockerfile

Second, I am not an expert in docker images. You will have to research for yourself why it does not work.

Usually you would prepare the Dockerfile, open a shell, try to run the failing command - often it will be missing some dependency or such.

Closing this, github issues are not for support for generic docker problems.
